window.TUTORIALS = {
	'Coconut Climbers':{},
	'Mystery Maze':{},
	'Volley Heads':{},
	'Soccer Heads':{},
	'Drum Beats':{},
	'Melody Match':{},
	'Coin Chaos':{},
	'Painter Panic':{},
	'Cardboard Cutout':{},
	'Stubble Trouble':{},
	'Milkers':{},
	'Popcorn Panhandlers':{},
	'Plummet Panic':{},
	'Cookie Cutter':{},
	'The Claw':{},
	'Spot The Meep':{},
	'Town Fair':{},
	'Goal Patrol':{},
	'Bowling Bonanza':{},
	'Final Frenzy':{},
}